name: publish CommonService

on:
  push:
    branches: [ "Development","main" ]
   # paths: [CommonService/**]
  pull_request:
    branches: [ "main" ]
   # paths: 
    #- CommonService/**

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: CommonService/mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: CommonService/mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
