name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: [UserService/**]
  pull_request:
    branches: [ "main" ]
    paths: 
    - UserService/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: UserService/mvn spring-boot:docker-image
